### ISSUE TITLE
wrong documentation for 'Global Installation'?

### ISSUE THREAD

**Issue by horacimacias** [L33T-KR3W/git-credential-env#6]
thanks for creating git-credential-env.

The steps shown to configure globally show the following:

```bash
git config credential.helper "env --username=GIT_USER --password=GIT_PASS"
```

perhaps you meant this instead?

```bash
git config credential.helper "git-credential-env --username=GIT_USER --password=GIT_PASS"
```

**Comment by rtsao** [comment]
This is interesting quirk with git, but `git credential-` is automatically prepended (see https://git-scm.com/docs/gitcredentials#_configuration_options)

So I believe it should work as-is.

**Comment by horacimacias** [comment]
oh, I see. My bad then; I was totally unaware of this.

thanks for clarifying!
